<a href="https://colab.research.google.com/github/abinioluwa/Discretised-vs-Continuous-Models-For-Predicting-Alzheimer-s-Disease-/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# @title
# import pandas for data manipulation and analysis
import pandas as pd
import numpy as np

# import matplotlib and seaborn for data visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# import libraries for data processsing
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import mutual_info_classif

# import machine learning (ML) algorithms
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

# import evaluation metrics
from sklearn.metrics import accuracy_score, classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import RocCurveDisplay



# Loading the Dataset

In [ ]:
# @title
# mount google drive
# from google.colab import drive
# drive.mount('/content/drive')

# import the dataset
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/investigator_nacc66.csv") # replace with file path on your machine

# Define list of infomartive features
features = ['NACCID','NACCVNUM', 'NACCBMI', 'BPSYS','BPDIAS', 'HRATE', 'VISION', 'VISCORR', 'VISWCORR','HEARING', 'HEARAID', 'HEARWAID', 'MEMORY',
            'ORIENT','JUDGMENT','COMMUN','HOMEHOBB','PERSCARE','COMPORT','CDRLANG',

            'TOBAC30', 'TOBAC100', 'SMOKYRS','PACKSPER','ALCOCCAS','QUITSMOK','ALCFREQ','CVHATT','HATTMULT','HATTYEAR','CVAFIB', 'CVANGIO', 'CVBYPASS',
            'CVPACDEF','CVPACE','CVCHF','CVANGINA','CVHVALVE','CVOTHR','CVOTHRX','CBSTROKE','STROKMUL','NACCSTYR','CBTIA','TIAMULT','NACCTIYR','PD',
            'PDYR','PDOTHR','PDOTHRYR','SEIZURES','NACCTBI', 'TBI','TBIBRIEF','TRAUMBRF','TBIEXTEN','TRAUMEXT','TBIWOLOS','TRAUMCHR','TBIYEAR','NCOTHR',
            'NCOTHRX', 'DIABETES','DIABTYPE','HYPERTEN','HYPERCHO','B12DEF','THYROID','ARTHRIT','ARTHTYPE','ARTHTYPX','ARTHUPEX','ARTHLOEX','ARTHSPIN',
            'ARTHUNK','INCONTU','INCONTF','APNEA','RBD','INSOMN','OTHSLEEP','OTHSLEEX','ALCOHOL','ABUSOTHR','ABUSX','PTSD','BIPOLAR','SCHIZ','DEP2YRS',
            'DEPOTHR','ANXIETY','OCD','NPSYDEV','PSYCDIS', 'PSYCDISX',

            'NOGDS','SATIS','DROPACT','EMPTY','BORED','SPIRITS','AFRAID','HAPPY','HELPLESS','STAYHOME','MEMPROB','WONDRFUL','WRTHLESS','ENERGY',
            'HOPELESS', 'BETTER','NACCGDS','NPIQINF','NPIQINFX','DEL','DELSEV','HALL','HALLSEV','AGIT','AGITSEV','DEPD','DEPDSEV','ANX','ANXSEV','ELAT',
            'ELATSEV', 'APA','APASEV','DISN','DISNSEV','IRR','IRRSEV','MOT','MOTSEV','NITE','NITESEV','APP','APPSEV','BILLS','TAXES','SHOPPING','GAMES',
            'STOVE','MEALPREP','EVENTS','PAYATTN','TRAVEL',

            'SEX','HISPANIC','HISPOR','HISPORX','RACE','RACEX','RACESEC','RACESECX','RACETER','RACETERX','PRIMLANG','PRIMLANX','EDUC','MARISTAT',
            'NACCLIVS','INDEPEND', 'RESIDENC','HANDED','NACCAGE','NACCNIHR','NACCUDSD']
df = df[features]
df.head()

<ipython-input-2-909008f31064>:6: DtypeWarning: Columns (20,22,24,26,28,41,44,46,48,51,61,63,65,67,69,71,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,134,156,165,176,179,189,217,220,222,224,226,228,230,232,234,236,238,240,242,244,246,248,250,252,254,256,258,260,262,264,266,268,270,272,382,397,399,401,419,421,423,432,445,454,494,574,605,613,638,674,690,704,707,710,715,727,738,744,746,803,804,809,810,811,812,820,831,833,835,837,843,904,959,960,961,969,970,971,972,982,1004,1007,1010) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/investigator_nacc66.csv") # replace with file path on your machine


NACCID  NACCVNUM  NACCBMI  BPSYS  BPDIAS  HRATE  VISION  VISCORR  \
0  NACC002909         1     32.4  160.0    85.0   59.0       0        1   
1  NACC002909         2     30.7  175.0    84.0   54.0       0        1   
2  NACC003487         1     23.7  149.0    86.0   83.0       9        9   
3  NACC004352         1    888.8  888.0   888.0  888.0       1        0   
4  NACC004687         1     19.0  148.0    75.0   70.0       0        1   

   VISWCORR  HEARING  ...  PRIMLANX  EDUC  MARISTAT  NACCLIVS  INDEPEND  \
0         1        1  ...       NaN    16         1         4         1   
1         1        1  ...       NaN    16         1         2         1   
2        -4        1  ...       NaN    16         1         2         1   
3         8        1  ...       NaN    16         1         2         2   
4         1        0  ...       NaN    12         3         1         1   

   RESIDENC  HANDED  NACCAGE  NACCNIHR  NACCUDSD  
0         1       2       70         1         3  
1         1       2       71         1         3  
2         1       2       66         1         1  
3         1       2       63         1         4  
4         1       2       77         1         1  

[5 rows x 168 columns]

# Understanding the Dataset

In [ ]:
# @title
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192088 entries, 0 to 192087
Columns: 168 entries, NACCID to NACCUDSD
dtypes: float64(12), int64(143), object(13)
memory usage: 246.2+ MB


NACCVNUM        NACCBMI          BPSYS         BPDIAS  \
count  192088.000000  192088.000000  191605.000000  191605.000000   
mean        3.804173      83.692539     168.575011     121.846335   
std         3.074937     222.034640     203.609393     212.468475   
min         1.000000      -4.000000      -4.000000      -4.000000   
25%         1.000000      22.100000     115.000000      64.000000   
50%         3.000000      25.800000     130.000000      73.000000   
75%         5.000000      30.300000     146.000000      82.000000   
max        19.000000     888.800000     888.000000     888.000000   

               HRATE         VISION        VISCORR       VISWCORR  \
count  191605.000000  192088.000000  192088.000000  192088.000000   
mean      114.266110      -0.151701       0.242165       1.583071   
std       210.673684       1.890663       1.914084       3.567958   
min        -4.000000      -4.000000      -4.000000      -4.000000   
25%        57.000000       0.000000       0.000000       1.000000   
50%        66.000000       0.000000       1.000000       1.000000   
75%        76.000000       1.000000       1.000000       1.000000   
max       888.000000       9.000000       9.000000       9.000000   

             HEARING        HEARAID  ...       PRIMLANG           EDUC  \
count  192088.000000  192088.000000  ...  192088.000000  192088.000000   
mean        0.235736      -0.287545  ...       1.177382      15.969904   
std         1.969774       1.754880  ...       0.930529       6.726524   
min        -4.000000      -4.000000  ...       1.000000       0.000000   
25%         0.000000       0.000000  ...       1.000000      13.000000   
50%         1.000000       0.000000  ...       1.000000      16.000000   
75%         1.000000       0.000000  ...       1.000000      18.000000   
max         9.000000       9.000000  ...       9.000000      99.000000   

            MARISTAT       NACCLIVS       INDEPEND       RESIDENC  \
count  192088.000000  192088.000000  192088.000000  192088.000000   
mean        1.776988       2.004774       1.539310       1.295760   
std         1.289254       0.900989       0.968471       1.105787   
min         1.000000       1.000000       1.000000       1.000000   
25%         1.000000       1.000000       1.000000       1.000000   
50%         1.000000       2.000000       1.000000       1.000000   
75%         2.000000       2.000000       2.000000       1.000000   
max         9.000000       9.000000       9.000000       9.000000   

              HANDED        NACCAGE       NACCNIHR       NACCUDSD  
count  192088.000000  192088.000000  192088.000000  192088.000000  
mean        1.977755      74.403529       2.647245       2.283948  
std         0.602375      10.300006      11.125252       1.328937  
min         1.000000      18.000000       1.000000       1.000000  
25%         2.000000      68.000000       1.000000       1.000000  
50%         2.000000      75.000000       1.000000       2.000000  
75%         2.000000      81.000000       1.000000       4.000000  
max         9.000000     110.000000      99.000000       4.000000  

[8 rows x 155 columns]

In [ ]:
# @title
# define a function to identify missing and unique values
def MissingUniqueStat(df):

  variable_name = []
  total_entry_list = []
  dtype_list = []
  unique_values_list = []
  number_of_unique_values = []
  number_of_missing_values = []
  ratio_of_missing_values = []

  for col in df.columns:
    variable_name.append(col)
    total_entry_list.append(len(df[col]))
    dtype_list.append(df[col].dtype)
    unique_values_list.append(df[col].unique())
    number_of_unique_values.append(df[col].nunique())
    number_of_missing_values.append(df[col].isna().sum())
    ratio_of_missing_values.append(df[col].isna().sum() / df.shape[0])

  data_info_df = pd.DataFrame({'Variable': variable_name,
                               '#_Total_Entry':total_entry_list,
                               '#_Missing_Value': number_of_missing_values,
                               '%_Missing_Value':ratio_of_missing_values,
                               'Data_Type': dtype_list,
                               'Unique_Values': unique_values_list,
                               '#_Unique_Values': number_of_unique_values
                               })

  data_info_df = data_info_df.set_index("Variable", inplace=False)

  return data_info_df.sort_values(by='#_Unique_Values', ascending=False)

In [ ]:
# @title
# apply the "MissingUniqueStat" function
data_info = MissingUniqueStat(df)
data_info

#_Total_Entry  #_Missing_Value  %_Missing_Value Data_Type  \
Variable                                                              
NACCID           192088                0         0.000000    object   
CVOTHRX          192088           176834         0.920588    object   
NCOTHRX          192088           186228         0.969493    object   
NPIQINFX         192088           152327         0.793006    object   
PSYCDISX         192088           183763         0.956660    object   
...                 ...              ...              ...       ...   
SPIRITS          192088                0         0.000000     int64   
BORED            192088                0         0.000000     int64   
HISPANIC         192088                0         0.000000     int64   
NOGDS            192088                0         0.000000     int64   
SEX              192088                0         0.000000     int64   

                                              Unique_Values  #_Unique_Values  
Variable                                                                      
NACCID    [NACC002909, NACC003487, NACC004352, NACC00468...            51836  
CVOTHRX   [nan, Quadruple Ablation, Coronary atheroscler...             6301  
NCOTHRX   [nan, confusion but no LOC in high school, pol...             3246  
NPIQINFX  [nan, Half-brother, cousin, Friend, Not Copart...             2374  
PSYCDISX  [nan, Wernicke Korsakoff, mood disorder nos, p...             2140  
...                                                     ...              ...  
SPIRITS                                       [0, -4, 1, 9]                4  
BORED                                         [0, -4, 1, 9]                4  
HISPANIC                                          [0, 1, 9]                3  
NOGDS                                            [0, -4, 1]                3  
SEX                                                  [1, 2]                2  

[168 rows x 6 columns]

# Split Dataset by Class Label

The target variable has 4 unique classes namely;
*   1 == Normal Cognition (NC)
*   2 == Impaired not MCI (nMCI)
*   3 == Mild Cognitive Impairment (MCI)
*   4 == Alzheimer's Disease (AD) or other Dementias

In [ ]:
# @title
# Splitting df into subsets based on target class in first visit
# NCvsAD = df_new.loc[df_new['NACCUDSD'].isin([1,4])] # Select only rows with target class enteries NC and AD
# NCvsMCI = df_new.loc[df_new['NACCUDSD'].isin([1,3])] # Select only rows with target class enteries NC and MCI
# MCIvsAD = df_new.loc[df_new['NACCUDSD'].isin([3,4])] # Select only rows with target class enteries MCI and AD
# NCvsMCIvsAD = df_new.loc[df_new['NACCUDSD'].isin([1,3,4])] # Select only rows with target class enteries NC, MCI and AD

NCvsAD = df.loc[df['NACCUDSD'].isin([1,4])] # Select only rows with target class enteries NC and AD
NCvsMCI = df.loc[df['NACCUDSD'].isin([1,3])] # Select only rows with target class enteries NC and MCI
MCIvsAD = df.loc[df['NACCUDSD'].isin([3,4])] # Select only rows with target class enteries MCI and AD
NCvsMCIvsAD = df.loc[df['NACCUDSD'].isin([1,3,4])] # Select only rows with target class enteries NC, MCI and AD

print(NCvsAD.shape)
print(NCvsMCI.shape)
print(MCIvsAD.shape)
print(NCvsMCIvsAD.shape)

(150092, 168)
(126611, 168)
(90577, 168)
(183640, 168)


# NC vs AD Discretised

In [ ]:
data_info = MissingUniqueStat(NCvsAD)
data_info

#_Total_Entry  #_Missing_Value  %_Missing_Value Data_Type  \
Variable                                                              
NACCID           150092                0         0.000000    object   
CVOTHRX          150092           138524         0.922927    object   
NCOTHRX          150092           145848         0.971724    object   
NPIQINFX         150092           119576         0.796685    object   
PSYCDISX         150092           144058         0.959798    object   
...                 ...              ...              ...       ...   
HEARAID          150092                0         0.000000     int64   
NOGDS            150092                0         0.000000     int64   
HISPANIC         150092                0         0.000000     int64   
SEX              150092                0         0.000000     int64   
NACCUDSD         150092                0         0.000000     int64   

                                              Unique_Values  #_Unique_Values  
Variable                                                                      
NACCID    [NACC003487, NACC004352, NACC004687, NACC00851...            43607  
CVOTHRX   [nan, Quadruple Ablation, Coronary atheroscler...             4991  
NCOTHRX   [nan, confusion but no LOC in high school, pol...             2468  
NPIQINFX  [nan, Half-brother, cousin, Friend, Not Copart...             1947  
PSYCDISX  [nan, Wernicke Korsakoff, mood disorder nos, p...             1637  
...                                                     ...              ...  
HEARAID                                       [0, 1, 9, -4]                4  
NOGDS                                            [0, -4, 1]                3  
HISPANIC                                          [0, 1, 9]                3  
SEX                                                  [1, 2]                2  
NACCUDSD                                             [1, 4]                2  

[168 rows x 6 columns]

## NCvsAD - Prepocessing

### Addressing Missing/Null Values

#### Replacing categorical null values
In this particular dataset, the missing/null value in the object columns conveys important information. Hence, we address their missing values by replacing them with a "empty" category.

In [ ]:
# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS          372
BPDIAS         372
HRATE          372
CVOTHRX     138524
NCOTHRX     145848
ARTHTYPX    149872
OTHSLEEX    149619
ABUSX       149180
PSYCDISX    144058
NPIQINFX    119576
HISPORX     149685
RACEX       148364
RACESECX    149860
RACETERX    150073
PRIMLANX    148144
dtype: int64


In [ ]:
# define function to replace categorical Null values with "empty" category
def impute_missing_categorical(df):
  categorical_cols = df.select_dtypes(include='object').columns
  for col in categorical_cols:
    df.loc[df[col].isna(), col] = 'empty'

  return df

In [ ]:
# @title
# replace Null values with "empty" category
NCvsAD = impute_missing_categorical(NCvsAD)

# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS     372
BPDIAS    372
HRATE     372
dtype: int64


#### Replacing Numerical Missing/Null Values
There are certain numerical values that represent missing/unkown values (i.e., 888.8, 88.8, 8.8, 9, 99, 999, 88, 888, -4 and 8888).
Hence we replace these values with NaN values to preserve data integrity



In [ ]:
# define function to replace missing/unknown values with NaN for uniformity

def replace_with_nan(df):
  numerical_cols = df.select_dtypes(include=['float64', 'int64']).columns
  for col in numerical_cols:
    df.loc[df[col] == 888.8, col] = np.nan
    df.loc[df[col] == 88.8, col] = np.nan
    df.loc[df[col] == 8.8, col] = np.nan
    df.loc[df[col] == 9, col] = np.nan
    df.loc[df[col] == 99, col] = np.nan
    df.loc[df[col] == 999, col] = np.nan
    df.loc[df[col] == 88, col] = np.nan
    df.loc[df[col] == 888, col] = np.nan
    df.loc[df[col] == -4, col] = np.nan
    df.loc[df[col] == 8888, col] = np.nan

  return df

In [ ]:
# @title
NCvsAD = replace_with_nan(NCvsAD)

# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

NACCVNUM     4083
NACCBMI     32594
BPSYS       32110
BPDIAS      34225
HRATE       33635
            ...  
INDEPEND      439
RESIDENC     1806
HANDED        830
NACCAGE      2787
NACCNIHR     1866
Length: 153, dtype: int64


In [ ]:
# define function to identify continuous and discrete features
def id_continuous(df, threshold=15):
  discrete_cols = [col for col in df.columns
                   if df[col].nunique() <= threshold and
                   df[col].dtype in ['int64', 'float64']]
  continuous_cols = [col for col in df.columns
                     if col not in discrete_cols and
                     df[col].dtype in ['int64', 'float64']]
  return discrete_cols, continuous_cols

# define function to process missing numerical values by replacing continuous features with the mean and discrete features with the mode
def impute_missing_numerical(df):
  # identify continuous and discrete columns
  discrete_cols, continuous_cols = id_continuous(df)

  # Fill remaining missing values using mean for continuous features and mode for categorical features
  for col in continuous_cols:
      df.loc[df[col].isna(), col] = df[col].mean()

  for col in discrete_cols:
    df.loc[df[col].isna(), col] = df[col].mode()[0]
  return df

In [ ]:
# @title
# replace missing/null values
NCvsAD = impute_missing_numerical(NCvsAD)

# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

Series([], dtype: int64)


### Removing Unmeaning Featues
This process removes features that lack variability, i.e., 90% or more of the values in the column are the same, which might not contribute significantly to the predictive power of a model


In [ ]:
# define function to rremove unmeaning features

def remove_unmeaning(df):
  # Calculate the percentage of the most frequent value for each column
  value_freq_ratio = df.apply(lambda x: x.value_counts(normalize=True).max())

  # Filter the columns with values with a 90% ratio frequency
  columns_to_drop = value_freq_ratio[value_freq_ratio >= 0.9].index
  df = df.drop(columns=columns_to_drop)

  return df


In [ ]:
# @title
NCvsAD = remove_unmeaning(NCvsAD)

# check
NCvsAD.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150092 entries, 2 to 192087
Data columns (total 74 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCID    150092 non-null  object 
 1   NACCVNUM  150092 non-null  float64
 2   NACCBMI   150092 non-null  float64
 3   BPSYS     150092 non-null  float64
 4   BPDIAS    150092 non-null  float64
 5   HRATE     150092 non-null  float64
 6   VISION    150092 non-null  float64
 7   VISCORR   150092 non-null  float64
 8   VISWCORR  150092 non-null  float64
 9   HEARING   150092 non-null  float64
 10  HEARAID   150092 non-null  float64
 11  HEARWAID  150092 non-null  float64
 12  MEMORY    150092 non-null  float64
 13  ORIENT    150092 non-null  float64
 14  JUDGMENT  150092 non-null  float64
 15  COMMUN    150092 non-null  float64
 16  HOMEHOBB  150092 non-null  float64
 17  PERSCARE  150092 non-null  float64
 18  COMPORT   150092 non-null  float64
 19  CDRLANG   150092 non-null  float64
 20  TOBAC100 

### Removing Outliers

In [ ]:
def remove_outliers(df, col_name):
  # identify lower and upper limits
  quartile1 = df[col_name].quantile(0.25)
  quartile3 = df[col_name].quantile(0.75)
  IQR = quartile3 - quartile1
  up_limit = quartile3 + (1.5 * IQR)
  low_limit = quartile1 - (1.5 * IQR)

  # replace outliers with median values
  df.loc[(df[col_name] < low_limit), col_name] = df[col_name].median()
  df.loc[(df[col_name] > up_limit), col_name] = df[col_name].median()

  return df

In [ ]:
# Apply remove_outliers function
for col in NCvsAD.columns:
  if NCvsAD[col].dtype in ['int64', 'float64']:
    NCvsAD = remove_outliers(NCvsAD, col)

### Addressing Object Variables

In [ ]:
# @title
for col in NCvsAD.columns:
  if NCvsAD[col].dtype in ['object']:
    print (col)

NACCID
NPIQINFX


The 'NPIQINFX' column metadata reads that it is information on the subject's co-participant. This does not necessarily affect diagnosis from a health perspective. Hence we drop it.

We also drop the 'NACCID' object column as it is not relevant to diagnosis

In [ ]:
NCvsAD = NCvsAD.drop(['NACCID', 'NPIQINFX'], axis=1)

NCvsAD.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150092 entries, 2 to 192087
Data columns (total 72 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCVNUM  150092 non-null  float64
 1   NACCBMI   150092 non-null  float64
 2   BPSYS     150092 non-null  float64
 3   BPDIAS    150092 non-null  float64
 4   HRATE     150092 non-null  float64
 5   VISION    150092 non-null  float64
 6   VISCORR   150092 non-null  float64
 7   VISWCORR  150092 non-null  float64
 8   HEARING   150092 non-null  float64
 9   HEARAID   150092 non-null  float64
 10  HEARWAID  150092 non-null  float64
 11  MEMORY    150092 non-null  float64
 12  ORIENT    150092 non-null  float64
 13  JUDGMENT  150092 non-null  float64
 14  COMMUN    150092 non-null  float64
 15  HOMEHOBB  150092 non-null  float64
 16  PERSCARE  150092 non-null  float64
 17  COMPORT   150092 non-null  float64
 18  CDRLANG   150092 non-null  float64
 19  TOBAC100  150092 non-null  float64
 20  SMOKYRS  

### Discretising Continuous Features

In [ ]:
discrete_cols, continuous_cols = id_continuous(NCvsAD)
print(continuous_cols)

['NACCBMI', 'BPSYS', 'BPDIAS', 'HRATE', 'SMOKYRS', 'EDUC', 'NACCAGE']


In [ ]:
# @title
# define function to discretise continuous features
def discretise(df):
  df['NACCBMI'] = pd.cut(df['NACCBMI'], bins = [0,18.5,25,30,100], labels=[0,1, 2,3])
  df['BPSYS'] = pd.cut(df['BPSYS'], bins = [0,90,140,250], labels=[0,1, 2])
  df['BPDIAS'] = pd.cut(df['BPDIAS'], bins = [0,60,90,250], labels=[0,1, 2])
  df['HRATE'] = pd.cut(df['HRATE'], bins = [0,60,100,250], labels=[0,1,0], ordered=False)
  df['SMOKYRS'] = pd.cut(df['SMOKYRS'], bins = [-1,15,30,100], labels=[0,1, 2])
  df['QUITSMOK'] = pd.cut(df['QUITSMOK'], bins = [-1,15,30,100], labels=[0,1, 2])
  df['EDUC'] = pd.cut(df['EDUC'], bins = [0,12,16,50], labels=[0,1, 2])
  df['NACCAGE'] = pd.cut(df['NACCAGE'], bins = [0,60,75,150], labels=[0,1,2])

  return df

In [ ]:
NCvsAD = discretise(NCvsAD)

# check
NCvsAD[continuous_cols].head()

NACCBMI BPSYS BPDIAS HRATE SMOKYRS EDUC NACCAGE
2       1     2      1     1       0    1       1
3       2     1      1     1       0    1       1
4       1     2      1     1       0    0       2
6       2     1      0     1       0    2       2
7       2     2      1     0       0    2       2

## Feature Selection

In [ ]:
def select_features_by_mutual_info(df, target, threshold=0.1):
    # Calculate mutual information between each feature and the target
    mi = mutual_info_classif(df.drop(target, axis=1), df[target], discrete_features=True)

    # Create a DataFrame with feature names and their MI values
    mi_df = pd.DataFrame({'Feature': df.drop(target, axis=1).columns, 'MI': mi})

    # Filter features with MI above the threshold
    features_to_keep = mi_df[mi_df['MI'] >= threshold]['Feature'].tolist()

    return features_to_keep

In [ ]:
features_to_keep = select_features_by_mutual_info(NCvsAD, 'NACCUDSD', threshold=0.1)
print(features_to_keep)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.1

['MEMORY', 'ORIENT', 'JUDGMENT', 'COMMUN', 'HOMEHOBB', 'BILLS', 'TAXES', 'SHOPPING', 'GAMES', 'MEALPREP', 'EVENTS', 'PAYATTN', 'TRAVEL', 'INDEPEND']


## Split into Training & Testing Sets

In [ ]:
# @title
X = NCvsAD[features_to_keep]
y = NCvsAD['NACCUDSD']
# First split: Training (70%) and Temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, stratify=y, random_state=42)

# Second split: Temporary set into Testing (15%) and Validation (15%)
X_test, X_valid, y_test, y_valid = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)
del (X_temp, y_temp)

print(f"Training set shape: {X_train.shape}, {y_train.shape}")
print(f"Validation set shape: {X_valid.shape}, {y_valid.shape}")
print(f"Test set shape: {X_test.shape}, {y_test.shape}")

Training set shape: (88627, 14), (88627,)
Validation set shape: (18992, 14), (18992,)
Test set shape: (18992, 14), (18992,)


## Modeling & Testing

In [ ]:
# @title
# define function to train 4 supervised models
def train_models(X_train, y_train):
    # Initialize models
    models = {
        'Random Forest': RandomForestClassifier(random_state=42),
        'KNN': KNeighborsClassifier(),
        'Naive Bayes': GaussianNB(),
        'SVM': SVC(kernel='linear', random_state=42)
    }

    # Dictionary to store trained models
    trained_models = {}

    # Train each model
    for name, model in models.items():
        model.fit(X_train, y_train)
        trained_models[name] = model
        print(f"{name} model trained.")

    return trained_models

In [ ]:
# @title
# define function to validate 4 supervised models
def validate_models(models, X_valid, y_valid):
    validation_results = {}

    # Validate each model
    for name, model in models.items():
        y_pred = model.predict(X_valid)
        accuracy = accuracy_score(y_valid, y_pred)
        validation_results[name] = accuracy
        print(f"{name} validation accuracy: {accuracy:.4f}")

    return validation_results

In [ ]:
# @title
# define function to test model performance
def test_models(models, X_test, y_test):
    test_results = {}

    # Test each model
    for name, model in models.items():
        y_pred = model.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        test_results[name] = accuracy
        print(f"{name} test accuracy: {accuracy:.4f}")
        print(f"{name} classification report:\n")
        print(classification_report(y_test, y_pred))

    return test_results

In [ ]:
# @title
trained_models = train_models(X_train, y_train)

Random Forest model trained.
KNN model trained.
Naive Bayes model trained.
SVM model trained.


In [ ]:
# @title
validation_results = validate_models(trained_models, X_valid, y_valid)

Random Forest validation accuracy: 0.9073
KNN validation accuracy: 0.8934
Naive Bayes validation accuracy: 0.7732
SVM validation accuracy: 0.9063


In [ ]:
# @title
test_results = test_models(trained_models, X_test, y_test)

Random Forest test accuracy: 0.9094
Random Forest classification report:

              precision    recall  f1-score   support

           1       0.95      0.92      0.94     13960
           3       0.80      0.87      0.84      5032

    accuracy                           0.91     18992
   macro avg       0.88      0.90      0.89     18992
weighted avg       0.91      0.91      0.91     18992

KNN test accuracy: 0.8947
KNN classification report:

              precision    recall  f1-score   support

           1       0.94      0.92      0.93     13960
           3       0.78      0.83      0.81      5032

    accuracy                           0.89     18992
   macro avg       0.86      0.87      0.87     18992
weighted avg       0.90      0.89      0.90     18992

Naive Bayes test accuracy: 0.7742
Naive Bayes classification report:

              precision    recall  f1-score   support

           1       0.93      0.75      0.83     13960
           3       0.55      0.85      

# NC vs MCI Discretised

In [ ]:
# @title
data_info = MissingUniqueStat(NCvsMCI)
data_info

#_Total_Entry  #_Missing_Value  %_Missing_Value Data_Type  \
Variable                                                              
NACCID           126611                0         0.000000    object   
CVOTHRX          126611           116931         0.923545    object   
NCOTHRX          126611           123138         0.972570    object   
NPIQINFX         126611            95064         0.750835    object   
PSYCDISX         126611           122028         0.963803    object   
...                 ...              ...              ...       ...   
HEARAID          126611                0         0.000000     int64   
NOGDS            126611                0         0.000000     int64   
HISPANIC         126611                0         0.000000     int64   
SEX              126611                0         0.000000     int64   
NACCUDSD         126611                0         0.000000     int64   

                                              Unique_Values  #_Unique_Values  
Variable                                                                      
NACCID    [NACC002909, NACC003487, NACC004687, NACC00721...            34187  
CVOTHRX   [nan, Quadruple Ablation, MVP, Mitral Valve Pr...             4325  
NCOTHRX   [nan, confusion but no LOC in high school, pol...             1950  
NPIQINFX  [nan, Half-brother, cousin, Friend, Not Copart...             1781  
PSYCDISX  [nan, panic attacks, Dissociate identity disor...             1281  
...                                                     ...              ...  
HEARAID                                       [0, 1, 9, -4]                4  
NOGDS                                            [0, -4, 1]                3  
HISPANIC                                          [0, 1, 9]                3  
SEX                                                  [1, 2]                2  
NACCUDSD                                             [3, 1]                2  

[168 rows x 6 columns]

## NCvsMCI - Prepocessing

### Addressing Missing/Null Values

#### Replacing categorical null values
In this particular dataset, the missing/null value in the object columns conveys important information. Hence, we address their missing values by replacing them with a "empty" category.

In [ ]:
# @title
# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS          319
BPDIAS         319
HRATE          319
CVOTHRX     116931
NCOTHRX     123138
ARTHTYPX    126433
OTHSLEEX    126199
ABUSX       125728
PSYCDISX    122028
NPIQINFX     95064
HISPORX     126232
RACEX       125595
RACESECX    126358
RACETERX    126588
PRIMLANX    124981
dtype: int64


In [ ]:
# @title
# replace Null values with "empty" category
NCvsMCI = impute_missing_categorical(NCvsMCI)

# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS     319
BPDIAS    319
HRATE     319
dtype: int64


#### Replacing Numerical Missing/Null Values
There are certain numerical values that represent missing/unkown values (i.e., 888.8, 88.8, 8.8, 9, 99, 999, 88, 888, -4 and 8888).
Hence we replace these values with NaN values to preserve data integrity



In [ ]:
# @title
NCvsMCI = replace_with_nan(NCvsMCI)

# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

NACCVNUM     3726
NACCBMI     20432
BPSYS       21532
BPDIAS      23483
HRATE       22690
            ...  
INDEPEND      230
RESIDENC     1675
HANDED        682
NACCAGE      2168
NACCNIHR     1130
Length: 153, dtype: int64


In [ ]:
# @title
# replace missing/null values
NCvsMCI = impute_missing_numerical(NCvsMCI)

# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

Series([], dtype: int64)


### Removing Unmeaning Featues
This process removes features that lack variability, i.e., 90% or more of the values in the column are the same, which might not contribute significantly to the predictive power of a model


In [ ]:
# @title
NCvsMCI = remove_unmeaning(NCvsMCI)

# check
NCvsMCI.info()

<class 'pandas.core.frame.DataFrame'>
Index: 126611 entries, 0 to 192085
Data columns (total 53 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCID    126611 non-null  object 
 1   NACCVNUM  126611 non-null  float64
 2   NACCBMI   126611 non-null  float64
 3   BPSYS     126611 non-null  float64
 4   BPDIAS    126611 non-null  float64
 5   HRATE     126611 non-null  float64
 6   VISION    126611 non-null  float64
 7   VISCORR   126611 non-null  float64
 8   VISWCORR  126611 non-null  float64
 9   HEARING   126611 non-null  float64
 10  HEARAID   126611 non-null  float64
 11  HEARWAID  126611 non-null  float64
 12  MEMORY    126611 non-null  float64
 13  JUDGMENT  126611 non-null  float64
 14  TOBAC100  126611 non-null  float64
 15  SMOKYRS   126611 non-null  float64
 16  PACKSPER  126611 non-null  float64
 17  QUITSMOK  126611 non-null  float64
 18  HYPERTEN  126611 non-null  float64
 19  HYPERCHO  126611 non-null  float64
 20  THYROID  

### Removing Outliers

In [ ]:
# @title
# Apply remove_outliers function
for col in NCvsMCI.columns:
  if NCvsMCI[col].dtype in ['int64', 'float64']:
    NCvsMCI = remove_outliers(NCvsMCI, col)

### Addressing Object Variables

In [ ]:
# @title
for col in NCvsMCI.columns:
  if NCvsMCI[col].dtype in ['object']:
    print (col)

NACCID
NPIQINFX


The 'NPIQINFX' column metadata reads that it is information on the subject's co-participant. This does not necessarily affect diagnosis from a health perspective. Hence we drop it.

We also drop the 'NACCID' object column as it is not relevant to diagnosis

In [ ]:
# @title
NCvsMCI = NCvsMCI.drop(['NACCID', 'NPIQINFX'], axis=1)

NCvsMCI.info()

<class 'pandas.core.frame.DataFrame'>
Index: 126611 entries, 0 to 192085
Data columns (total 51 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCVNUM  126611 non-null  float64
 1   NACCBMI   126611 non-null  float64
 2   BPSYS     126611 non-null  float64
 3   BPDIAS    126611 non-null  float64
 4   HRATE     126611 non-null  float64
 5   VISION    126611 non-null  float64
 6   VISCORR   126611 non-null  float64
 7   VISWCORR  126611 non-null  float64
 8   HEARING   126611 non-null  float64
 9   HEARAID   126611 non-null  float64
 10  HEARWAID  126611 non-null  float64
 11  MEMORY    126611 non-null  float64
 12  JUDGMENT  126611 non-null  float64
 13  TOBAC100  126611 non-null  float64
 14  SMOKYRS   126611 non-null  float64
 15  PACKSPER  126611 non-null  float64
 16  QUITSMOK  126611 non-null  float64
 17  HYPERTEN  126611 non-null  float64
 18  HYPERCHO  126611 non-null  float64
 19  THYROID   126611 non-null  float64
 20  INCONTU  

### Discretising Continuous Features

In [ ]:
# @title
discrete_cols, continuous_cols = id_continuous(NCvsMCI)
print(continuous_cols)

['NACCBMI', 'BPSYS', 'BPDIAS', 'HRATE', 'SMOKYRS', 'EDUC', 'NACCAGE']


In [ ]:
# @title
NCvsMCI = discretise(NCvsMCI)

# check
NCvsMCI[continuous_cols].head()

NACCBMI BPSYS BPDIAS HRATE SMOKYRS EDUC NACCAGE
0       3     2      1     0       0    1       1
1       3     1      1     0       0    1       1
2       1     2      1     1       0    1       1
4       1     2      1     1       0    0       2
5       1     1      1     0       0    1       2

## Feature Selection

In [ ]:
# @title
features_to_keep = select_features_by_mutual_info(NCvsMCI, 'NACCUDSD', threshold=0.1)
print(features_to_keep)

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/cluster/_supervised.py:66: UserWarning: Clustering metrics expects discrete values but received continuous values for label, and binary values for target
  warnings.warn(msg, UserWarning)


['MEMORY']


Feature Selection by mutual information (MI) returned only 1 feature to keep. Hence, we use Recursive Feature Elimination (RFE) to select the top 14 features

In [ ]:
# @title
from sklearn.feature_selection import RFE

#train-test split data
X = NCvsMCI.drop(columns=['NACCUDSD'])  # Features excluding the target
y = NCvsMCI['NACCUDSD']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)

# model RFE
estimator = RandomForestClassifier(random_state=42)
rfe = RFE(estimator=estimator, n_features_to_select=14)  # Select top 10 features
rfe.fit(X_train, y_train)

# Get the selected features
selected_features = X.columns[rfe.support_]
print("Selected features:", selected_features)

Selected features: Index(['NACCVNUM', 'NACCBMI', 'BPSYS', 'HRATE', 'MEMORY', 'PACKSPER',
       'HYPERTEN', 'HYPERCHO', 'NACCGDS', 'NPIQINF', 'EDUC', 'MARISTAT',
       'NACCLIVS', 'NACCAGE'],
      dtype='object')


In [ ]:
# @title
# Evaluate Model Performance
X_train_rfe = rfe.transform(X_train)
X_test_rfe = rfe.transform(X_test)

# Train the model on the selected features
estimator.fit(X_train_rfe, y_train)

# Predict on the test set
y_pred = estimator.predict(X_test_rfe)

# Evaluate the accuracy
accuracy = accuracy_score(y_test, y_pred)
print(f"Model accuracy with selected features: {accuracy:.4f}")

Model accuracy with selected features: 0.8925


## Split into Training & Testing Sets

In [ ]:
# @title
X = NCvsMCI[selected_features]
y = NCvsMCI['NACCUDSD']
# First split: Training (70%) and Temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, stratify=y, random_state=42)

# Second split: Temporary set into Testing (15%) and Validation (15%)
X_test, X_valid, y_test, y_valid = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)
del (X_temp, y_temp)

print(f"Training set shape: {X_train.shape}, {y_train.shape}")
print(f"Validation set shape: {X_valid.shape}, {y_valid.shape}")
print(f"Test set shape: {X_test.shape}, {y_test.shape}")

Training set shape: (88627, 14), (88627,)
Validation set shape: (18992, 14), (18992,)
Test set shape: (18992, 14), (18992,)


## Modeling & Testing

In [ ]:
# @title
trained_models = train_models(X_train, y_train)

Random Forest model trained.
KNN model trained.
Naive Bayes model trained.
SVM model trained.


In [ ]:
# @title
validation_results = validate_models(trained_models, X_valid, y_valid)

Random Forest validation accuracy: 0.8919
KNN validation accuracy: 0.8221
Naive Bayes validation accuracy: 0.9053
SVM validation accuracy: 0.9054


In [ ]:
# @title
test_results = test_models(trained_models, X_test, y_test)

Random Forest test accuracy: 0.8930
Random Forest classification report:

              precision    recall  f1-score   support

         1.0       0.93      0.92      0.93     13960
         3.0       0.79      0.82      0.80      5032

    accuracy                           0.89     18992
   macro avg       0.86      0.87      0.86     18992
weighted avg       0.89      0.89      0.89     18992

KNN test accuracy: 0.8238
KNN classification report:

              precision    recall  f1-score   support

         1.0       0.84      0.93      0.89     13960
         3.0       0.74      0.52      0.61      5032

    accuracy                           0.82     18992
   macro avg       0.79      0.73      0.75     18992
weighted avg       0.82      0.82      0.81     18992

Naive Bayes test accuracy: 0.9075
Naive Bayes classification report:

              precision    recall  f1-score   support

         1.0       0.95      0.92      0.94     13960
         3.0       0.80      0.88      

# REPEAT PROCEDURE ON NON-DISCRETISED CONTINUOUS DATA

In [ ]:
# @title
NCvsAD = df.loc[df['NACCUDSD'].isin([1,4])] # Select only rows with target class enteries NC and AD
NCvsMCI = df.loc[df['NACCUDSD'].isin([1,3])] # Select only rows with target class enteries NC and MCI
MCIvsAD = df.loc[df['NACCUDSD'].isin([3,4])] # Select only rows with target class enteries MCI and AD
NCvsMCIvsAD = df.loc[df['NACCUDSD'].isin([1,3,4])] # Select only rows with target class enteries NC, MCI and AD

print(NCvsAD.shape)
print(NCvsMCI.shape)
print(MCIvsAD.shape)
print(NCvsMCIvsAD.shape)

(150092, 168)
(126611, 168)
(90577, 168)
(183640, 168)


# NC vs AD Continuous

## NCvsAD - Prepocessing

### Addressing Missing/Null Values

#### Replacing categorical null values
In this particular dataset, the missing/null value in the object columns conveys important information. Hence, we address their missing values by replacing them with a "empty" category.

In [ ]:
# @title
# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS          372
BPDIAS         372
HRATE          372
CVOTHRX     138524
NCOTHRX     145848
ARTHTYPX    149872
OTHSLEEX    149619
ABUSX       149180
PSYCDISX    144058
NPIQINFX    119576
HISPORX     149685
RACEX       148364
RACESECX    149860
RACETERX    150073
PRIMLANX    148144
dtype: int64


In [ ]:
# @title
# replace Null values with "empty" category
NCvsAD = impute_missing_categorical(NCvsAD)

# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS     372
BPDIAS    372
HRATE     372
dtype: int64


#### Replacing Numerical Missing/Null Values
There are certain numerical values that represent missing/unkown values (i.e., 888.8, 88.8, 8.8, 9, 99, 999, 88, 888, -4 and 8888).
Hence we replace these values with NaN values to preserve data integrity



In [ ]:
# @title
NCvsAD = replace_with_nan(NCvsAD)

# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

NACCVNUM     4083
NACCBMI     32594
BPSYS       32110
BPDIAS      34225
HRATE       33635
            ...  
INDEPEND      439
RESIDENC     1806
HANDED        830
NACCAGE      2787
NACCNIHR     1866
Length: 153, dtype: int64


In [ ]:
# @title
# replace missing/null values
NCvsAD = impute_missing_numerical(NCvsAD)

# check for null values
nan_counts = NCvsAD.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

Series([], dtype: int64)


### Removing Unmeaning Featues
This process removes features that lack variability, i.e., 90% or more of the values in the column are the same, which might not contribute significantly to the predictive power of a model


In [ ]:
# @title
NCvsAD = remove_unmeaning(NCvsAD)

# check
NCvsAD.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150092 entries, 2 to 192087
Data columns (total 74 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCID    150092 non-null  object 
 1   NACCVNUM  150092 non-null  float64
 2   NACCBMI   150092 non-null  float64
 3   BPSYS     150092 non-null  float64
 4   BPDIAS    150092 non-null  float64
 5   HRATE     150092 non-null  float64
 6   VISION    150092 non-null  float64
 7   VISCORR   150092 non-null  float64
 8   VISWCORR  150092 non-null  float64
 9   HEARING   150092 non-null  float64
 10  HEARAID   150092 non-null  float64
 11  HEARWAID  150092 non-null  float64
 12  MEMORY    150092 non-null  float64
 13  ORIENT    150092 non-null  float64
 14  JUDGMENT  150092 non-null  float64
 15  COMMUN    150092 non-null  float64
 16  HOMEHOBB  150092 non-null  float64
 17  PERSCARE  150092 non-null  float64
 18  COMPORT   150092 non-null  float64
 19  CDRLANG   150092 non-null  float64
 20  TOBAC100 

### Removing Outliers

In [ ]:
# @title
# Apply remove_outliers function
for col in NCvsAD.columns:
  if NCvsAD[col].dtype in ['int64', 'float64']:
    NCvsAD = remove_outliers(NCvsAD, col)

### Addressing Object Variables

In [ ]:
# @title
for col in NCvsAD.columns:
  if NCvsAD[col].dtype in ['object']:
    print (col)

NACCID
NPIQINFX


The 'NPIQINFX' column metadata reads that it is information on the subject's co-participant. This does not necessarily affect diagnosis from a health perspective. Hence we drop it.

We also drop the 'NACCID' object column as it is not relevant to diagnosis

In [ ]:
# @title
NCvsAD = NCvsAD.drop(['NACCID', 'NPIQINFX'], axis=1)

NCvsAD.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150092 entries, 2 to 192087
Data columns (total 72 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCVNUM  150092 non-null  float64
 1   NACCBMI   150092 non-null  float64
 2   BPSYS     150092 non-null  float64
 3   BPDIAS    150092 non-null  float64
 4   HRATE     150092 non-null  float64
 5   VISION    150092 non-null  float64
 6   VISCORR   150092 non-null  float64
 7   VISWCORR  150092 non-null  float64
 8   HEARING   150092 non-null  float64
 9   HEARAID   150092 non-null  float64
 10  HEARWAID  150092 non-null  float64
 11  MEMORY    150092 non-null  float64
 12  ORIENT    150092 non-null  float64
 13  JUDGMENT  150092 non-null  float64
 14  COMMUN    150092 non-null  float64
 15  HOMEHOBB  150092 non-null  float64
 16  PERSCARE  150092 non-null  float64
 17  COMPORT   150092 non-null  float64
 18  CDRLANG   150092 non-null  float64
 19  TOBAC100  150092 non-null  float64
 20  SMOKYRS  

## Feature Selection

We conduct Spearman's Rank Correlation since it's applicable to both discrete and continuous data

In [ ]:
# @title
from scipy.stats import spearmanr

del features_to_keep
features_to_keep = []

for col in NCvsAD.columns:
  if NCvsAD[col].dtype in ['int64', 'float64']:
    corr, _ = spearmanr(NCvsAD[col], NCvsAD['NACCUDSD'])
    if abs(corr) > 0.1:
      features_to_keep.append(col)

print(features_to_keep)


<ipython-input-87-a847c3603e2d>:8: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  corr, _ = spearmanr(NCvsAD[col], NCvsAD['NACCUDSD'])


['NACCVNUM', 'MEMORY', 'ORIENT', 'JUDGMENT', 'COMMUN', 'HOMEHOBB', 'NPIQINF', 'BILLS', 'TAXES', 'SHOPPING', 'GAMES', 'STOVE', 'MEALPREP', 'EVENTS', 'PAYATTN', 'TRAVEL', 'SEX', 'EDUC', 'INDEPEND', 'NACCUDSD']


## Split into Training & Testing Sets

In [ ]:
# @title
X = NCvsAD[features_to_keep]
y = NCvsAD['NACCUDSD']
# First split: Training (70%) and Temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, stratify=y, random_state=42)

# Second split: Temporary set into Testing (15%) and Validation (15%)
X_test, X_valid, y_test, y_valid = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)
del (X_temp, y_temp)

print(f"Training set shape: {X_train.shape}, {y_train.shape}")
print(f"Validation set shape: {X_valid.shape}, {y_valid.shape}")
print(f"Test set shape: {X_test.shape}, {y_test.shape}")

Training set shape: (105064, 20), (105064,)
Validation set shape: (22514, 20), (22514,)
Test set shape: (22514, 20), (22514,)


## Modeling & Testing

In [ ]:
# @title
trained_models = train_models(X_train, y_train)

Random Forest model trained.
KNN model trained.
Naive Bayes model trained.
SVM model trained.


In [ ]:
# @title
validation_results = validate_models(trained_models, X_valid, y_valid)

Random Forest validation accuracy: 1.0000
KNN validation accuracy: 1.0000
Naive Bayes validation accuracy: 1.0000
SVM validation accuracy: 1.0000


In [ ]:
# @title
test_results = test_models(trained_models, X_test, y_test)

Random Forest test accuracy: 1.0000
Random Forest classification report:

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     13960
         4.0       1.00      1.00      1.00      8554

    accuracy                           1.00     22514
   macro avg       1.00      1.00      1.00     22514
weighted avg       1.00      1.00      1.00     22514

KNN test accuracy: 0.9999
KNN classification report:

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     13960
         4.0       1.00      1.00      1.00      8554

    accuracy                           1.00     22514
   macro avg       1.00      1.00      1.00     22514
weighted avg       1.00      1.00      1.00     22514

Naive Bayes test accuracy: 1.0000
Naive Bayes classification report:

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     13960
         4.0       1.00      1.00      

# NC vs MCI Continuous

## NCvsMCI - Prepocessing

### Addressing Missing/Null Values

#### Replacing categorical null values
In this particular dataset, the missing/null value in the object columns conveys important information. Hence, we address their missing values by replacing them with a "empty" category.

In [ ]:
# @title
# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS          319
BPDIAS         319
HRATE          319
CVOTHRX     116931
NCOTHRX     123138
ARTHTYPX    126433
OTHSLEEX    126199
ABUSX       125728
PSYCDISX    122028
NPIQINFX     95064
HISPORX     126232
RACEX       125595
RACESECX    126358
RACETERX    126588
PRIMLANX    124981
dtype: int64


In [ ]:
# @title
# replace Null values with "empty" category
NCvsMCI = impute_missing_categorical(NCvsMCI)

# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

BPSYS     319
BPDIAS    319
HRATE     319
dtype: int64


#### Replacing Numerical Missing/Null Values
There are certain numerical values that represent missing/unkown values (i.e., 888.8, 88.8, 8.8, 9, 99, 999, 88, 888, -4 and 8888).
Hence we replace these values with NaN values to preserve data integrity



In [ ]:
# @title
NCvsMCI = replace_with_nan(NCvsMCI)

# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

NACCVNUM     3726
NACCBMI     20432
BPSYS       21532
BPDIAS      23483
HRATE       22690
            ...  
INDEPEND      230
RESIDENC     1675
HANDED        682
NACCAGE      2168
NACCNIHR     1130
Length: 153, dtype: int64


In [ ]:
# @title
# replace missing/null values
NCvsMCI = impute_missing_numerical(NCvsMCI)

# check for null values
nan_counts = NCvsMCI.isna().sum()
nan_columns = nan_counts[nan_counts > 0]
print(nan_columns)

Series([], dtype: int64)


### Removing Unmeaning Featues
This process removes features that lack variability, i.e., 90% or more of the values in the column are the same, which might not contribute significantly to the predictive power of a model


In [ ]:
# @title
NCvsMCI = remove_unmeaning(NCvsMCI)

# check
NCvsMCI.info()

<class 'pandas.core.frame.DataFrame'>
Index: 126611 entries, 0 to 192085
Data columns (total 53 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCID    126611 non-null  object 
 1   NACCVNUM  126611 non-null  float64
 2   NACCBMI   126611 non-null  float64
 3   BPSYS     126611 non-null  float64
 4   BPDIAS    126611 non-null  float64
 5   HRATE     126611 non-null  float64
 6   VISION    126611 non-null  float64
 7   VISCORR   126611 non-null  float64
 8   VISWCORR  126611 non-null  float64
 9   HEARING   126611 non-null  float64
 10  HEARAID   126611 non-null  float64
 11  HEARWAID  126611 non-null  float64
 12  MEMORY    126611 non-null  float64
 13  JUDGMENT  126611 non-null  float64
 14  TOBAC100  126611 non-null  float64
 15  SMOKYRS   126611 non-null  float64
 16  PACKSPER  126611 non-null  float64
 17  QUITSMOK  126611 non-null  float64
 18  HYPERTEN  126611 non-null  float64
 19  HYPERCHO  126611 non-null  float64
 20  THYROID  

### Removing Outliers

In [ ]:
# @title
# Apply remove_outliers function
for col in NCvsMCI.columns:
  if NCvsMCI[col].dtype in ['int64', 'float64']:
    NCvsMCI = remove_outliers(NCvsMCI, col)

### Addressing Object Variables

In [ ]:
# @title
for col in NCvsMCI.columns:
  if NCvsMCI[col].dtype in ['object']:
    print (col)

NACCID
NPIQINFX


The 'NPIQINFX' column metadata reads that it is information on the subject's co-participant. This does not necessarily affect diagnosis from a health perspective. Hence we drop it.

We also drop the 'NACCID' object column as it is not relevant to diagnosis

In [ ]:
# @title
NCvsMCI = NCvsMCI.drop(['NACCID', 'NPIQINFX'], axis=1)

NCvsMCI.info()

<class 'pandas.core.frame.DataFrame'>
Index: 126611 entries, 0 to 192085
Data columns (total 51 columns):
 #   Column    Non-Null Count   Dtype  
---  ------    --------------   -----  
 0   NACCVNUM  126611 non-null  float64
 1   NACCBMI   126611 non-null  float64
 2   BPSYS     126611 non-null  float64
 3   BPDIAS    126611 non-null  float64
 4   HRATE     126611 non-null  float64
 5   VISION    126611 non-null  float64
 6   VISCORR   126611 non-null  float64
 7   VISWCORR  126611 non-null  float64
 8   HEARING   126611 non-null  float64
 9   HEARAID   126611 non-null  float64
 10  HEARWAID  126611 non-null  float64
 11  MEMORY    126611 non-null  float64
 12  JUDGMENT  126611 non-null  float64
 13  TOBAC100  126611 non-null  float64
 14  SMOKYRS   126611 non-null  float64
 15  PACKSPER  126611 non-null  float64
 16  QUITSMOK  126611 non-null  float64
 17  HYPERTEN  126611 non-null  float64
 18  HYPERCHO  126611 non-null  float64
 19  THYROID   126611 non-null  float64
 20  INCONTU  

## Feature Selection

We conduct Spearman's Rank Correlation since it's applicable to both discrete and continuous data

In [ ]:
# @title
del features_to_keep
features_to_keep = []

for col in NCvsMCI.columns:
  if NCvsMCI[col].dtype in ['int64', 'float64']:
    corr, _ = spearmanr(NCvsMCI[col], NCvsMCI['NACCUDSD'])
    if abs(corr) > 0.1:
      features_to_keep.append(col)

print(features_to_keep)


<ipython-input-106-3b56db45d5b9>:6: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  corr, _ = spearmanr(NCvsMCI[col], NCvsMCI['NACCUDSD'])


['NACCVNUM', 'MEMORY', 'NACCGDS', 'SEX', 'NACCUDSD']


## Split into Training & Testing Sets

In [ ]:
# @title
X = NCvsMCI[features_to_keep]
y = NCvsMCI['NACCUDSD']
# First split: Training (70%) and Temporary set (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.30, stratify=y, random_state=42)

# Second split: Temporary set into Testing (15%) and Validation (15%)
X_test, X_valid, y_test, y_valid = train_test_split(X_temp, y_temp, test_size=0.50, stratify=y_temp, random_state=42)
del (X_temp, y_temp)

print(f"Training set shape: {X_train.shape}, {y_train.shape}")
print(f"Validation set shape: {X_valid.shape}, {y_valid.shape}")
print(f"Test set shape: {X_test.shape}, {y_test.shape}")

Training set shape: (88627, 5), (88627,)
Validation set shape: (18992, 5), (18992,)
Test set shape: (18992, 5), (18992,)


## Modeling & Testing

In [ ]:
# @title
trained_models = train_models(X_train, y_train)

Random Forest model trained.
KNN model trained.
Naive Bayes model trained.
SVM model trained.


In [ ]:
# @title
validation_results = validate_models(trained_models, X_valid, y_valid)

Random Forest validation accuracy: 1.0000
KNN validation accuracy: 1.0000
Naive Bayes validation accuracy: 1.0000
SVM validation accuracy: 1.0000


In [ ]:
# @title
test_results = test_models(trained_models, X_test, y_test)

Random Forest test accuracy: 1.0000
Random Forest classification report:

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     13960
         3.0       1.00      1.00      1.00      5032

    accuracy                           1.00     18992
   macro avg       1.00      1.00      1.00     18992
weighted avg       1.00      1.00      1.00     18992

KNN test accuracy: 1.0000
KNN classification report:

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     13960
         3.0       1.00      1.00      1.00      5032

    accuracy                           1.00     18992
   macro avg       1.00      1.00      1.00     18992
weighted avg       1.00      1.00      1.00     18992

Naive Bayes test accuracy: 1.0000
Naive Bayes classification report:

              precision    recall  f1-score   support

         1.0       1.00      1.00      1.00     13960
         3.0       1.00      1.00      